version: '3'

services: 
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql/db:/var/lib/mysql
      - ./mysql/script:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
  
  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    volumes: 
      - ./node:/usr/src/app
    ports: 
      - "3000:3000"
    tty: true
    depends_on: 
      - db